urls.py
#! -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url, include
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'wirgul.web.views.main', name='main_view'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^captcha/', include('captcha.urls')),
    (r'^user/', include('wirgul.web.urls')),
)

if settings.DEVELOPMENT_SERVER:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

web/models.py
#! -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from wirgul.utils.messages import WEB_MODEL_EMAIL, WEB_MODEL_MIDDLE_NAME, WEB_MODEL_SURNAME, WEB_MODEL_YOURNAME, \
    WEB_MODEL_FACULTY, WEB_MODEL_DEPARTMENT, WEB_MODEL_GUEST_EMAIL, WEB_MODEL_CHOOSE_DURATION_TYPE, \
    WEB_MODEL_CHOOSE_DURATION, WEB_MODEL_TEL_NUMBER, WEB_MODEL_CITIZEN

class Faculty(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return u'%s' % (self.name)

class Department(models.Model):
    name = models.CharField(max_length=200)
    faculty = models.ForeignKey(Faculty)

    def __unicode__(self):
        return u'%s' % (self.name)

class Url(models.Model):
    url_id = models.CharField(max_length=100)
    url_create_time = models.DateTimeField(auto_now=True) # urlin ilk oluşturulduğu zaman
    status = models.BooleanField(default=False) # url e tıklama durumu kontrolü

class FirstTimeUserSecret(models.Model):
    passwd_change_time = models.DateTimeField(auto_now=True)

class PasswordChange(models.Model):
    email = models.EmailField(verbose_name=_(WEB_MODEL_EMAIL))
    url = models.ForeignKey(Url, blank=True, null=True)

class FirstTimeUser(models.Model):
    name = models.CharField(verbose_name=_(WEB_MODEL_YOURNAME),max_length=50)
    middle_name = models.CharField(verbose_name=_(WEB_MODEL_MIDDLE_NAME),max_length=50, null=True, blank=True)
    surname = models.CharField(verbose_name=_(WEB_MODEL_SURNAME),max_length=100)
    faculty = models.ForeignKey(Faculty,verbose_name=_(WEB_MODEL_FACULTY))
    department = models.ForeignKey(Department,verbose_name=_(WEB_MODEL_DEPARTMENT))
    email = models.EmailField(verbose_name=_(WEB_MODEL_EMAIL))
    url = models.ForeignKey(Url, blank=True, null=True)
    secret = models.ForeignKey(FirstTimeUserSecret, blank=True,null=True)

class GuestUser(models.Model):
    name = models.CharField(verbose_name=_(WEB_MODEL_YOURNAME),max_length=50)
    middle_name = models.CharField(verbose_name=_(WEB_MODEL_MIDDLE_NAME),max_length=50, null=True, blank=True)
    surname = models.CharField(verbose_name=_(WEB_MODEL_SURNAME),max_length=100)
    guest_user_email = models.EmailField(verbose_name=_(WEB_MODEL_EMAIL))
    email = models.EmailField(verbose_name=_(WEB_MODEL_GUEST_EMAIL))
    guest_user_phone = models.FloatField(WEB_MODEL_TEL_NUMBER)
    url = models.ForeignKey(Url, blank=True, null=True)
    TIME_CHOICES = (
        (1, 'SAAT'),
        (2, 'GUN'),
        (3, 'HAFTA'),
        )
    type = models.SmallIntegerField(blank=True,null=True,choices=TIME_CHOICES,default=1,max_length=10,verbose_name=_(WEB_MODEL_CHOOSE_DURATION_TYPE))
    time_duration = models.IntegerField(blank=True,null=True,choices=settings.TIME_DURATION_CHOICES,verbose_name=_(WEB_MODEL_CHOOSE_DURATION), max_length=10)
    application_time = models.DateTimeField(blank=True, null=True)
    deadline_time = models.DateTimeField(blank=True, null=True)
    citizen_no = models.CharField(verbose_name=_(WEB_MODEL_CITIZEN), max_length=20)
    status = models.BooleanField(default=False)

templates/main/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ page_title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/site_media/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="/site_media/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/site_media/bootstrap/assets/ico/favicon-wirgul.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/site_media/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/site_media/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/site_media/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/site_media/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="{% url main_view %}">{% trans main_page %}</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li {% ifequal web "new_user" %} class="active" {% endifequal %}><a href="{% url new_user_view %}">{% trans "New User Application" %}</a></li>
                    <li {% ifequal web "guest_user" %} class="active" {% endifequal %}><a href="{% url guest_user_view %}">{%  trans "Guest User" %}</a></li>
                    <li {% ifequal web "password_change" %} class="active" {% endifequal %}><a href="{% url new_password_view %}">{% trans "New Password" %}</a></li>
                </ul>

                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Language" %}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            {% for lang in LANGUAGES %}
                                <li>
                                    <form name="setLang{{ lang.1}}" action="/i18n/setlang/" method="POST">{% csrf_token %}
                                        <input name="next" type="hidden" value="/" />
                                        <input type="hidden" name="language" value="{{ lang.0 }}" />
                                        <a href="#" onclick="document.setLang{{ lang.1 }}.submit();return false;">{{ lang.1 }}</a>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>

            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">

{% block language %}
{% endblock %}
    {% block content %}{% endblock %}

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/site_media/bootstrap/assets/js/jquery.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-transition.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-alert.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-modal.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-scrollspy.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-tab.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-tooltip.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-popover.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-button.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-collapse.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-carousel.js"></script>
<script src="/site_media/bootstrap/assets/js/bootstrap-typeahead.js"></script>

    {% ifequal web 'new_user' %}
        <script>
            var faculty_id = "";
            $(document).ready(function() {
                $("#id_faculty").change(function () {
                    faculty_id = $(this).attr('value');
                    $.post("{% url get_departments %}", {"id": faculty_id, 'csrfmiddlewaretoken': "{{ csrf_token }}"},function(data) {
                        var deparment_lenght = $('#id_department option').length;
                        for(i=0;i<deparment_lenght;i++){
                            $("#id_department option:selected").remove();
                        }
                        $('#id_department').append(data);
                    });
                });

            });
        </script>
    {% endifequal %}

</body>
</html>

templates/main/extend.html
{% extends "base.html" %}
{% block icerik %}  Extend {% endblock %}

templates/main/info.html
{% extends "main/base.html" %}
{% load i18n %}

{% block content %}
{% ifequal info 'guest_user_already_exist' %}
    <h3>
        {% url new_password_view as new_password_view_url %}
        {% blocktrans %}
        <p>There is an account already exist with th email address {{ email }} on our system.</p>
        <p>Connection details had been sent to your email. You can see your previous details by searching your email inbox.</p>
        <p>If you don't remember your password use <a href="{{ new_password_view_url }}">New Password menu</a>
            to get a new password to your email.</p>
         {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'new_user_already_exist' %}
    <h3>
        {% url new_password_view as new_password_view_url %}
        {% blocktrans %}
        <p>{{ email }} address is already registered.</p>
        <p>Use <a href="{{ new_password_view_url }}">New Password menu</a> to get a new password to your email.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'host_user_invalid' %}
    {% blocktrans %}
    <h3> A user with the address {{ host_user_email }} is not registered to our system.</h3>
    {% endblocktrans %}
    {% endifequal %}
{% ifequal info 'password_change_invalid_mail' %}
    <h3>
        {% url new_user_view as new_user_view_url %}
        {% blocktrans %}
        <p>The email that you entered is not registered to our system.</p>
        <p> To register a new user click <a href="{{ new_user_view_url }}">link</a>.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
 {% endifequal %}
{% ifequal info 'mail_confirm' %}
<h3>
    {% blocktrans %}
    <p>Click on the link sent to the address ({{ email }}) to fulfill the account creation.</p>
    {% endblocktrans %}
</h3>
 <div class="row">
     <div class="offset4 span4">
         <img src="/site_media/images/check.png" alt="{% trans 'Warning' %}" >
     </div>
 </div>
{% endifequal %}
{% ifequal info 'guest_mail_confirm' %}
    <h3>
        {% blocktrans %}
        <p>When ever the link is clicked at the email address {{ host_email }} the wireless connection details related
            with {{ email }} will be sent.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/check.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'password_change_mail_confirm' %}
    <h3>
        {% blocktrans %}
        <p>You can click the link sent to the address ({{ email }}) and the new password will be sent to your email.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/check.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'new_user_already_exists' %}
    <h3>
        {% url new_password_view as new_password_view_url %}
        {% blocktrans %}
        <p>You had registered before by clicking this link.</p>
        <p>If you forget your password use <a href="{{ new_password_view_url }}">New Password menu</a>
            to get a new password to your email address.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'guest_user_already_exists' %}
    <h3>
        {% url new_password_view as new_password_view_url %}
        {% blocktrans %}
        <p>You had registered before by clicking this link.</p>
        <p>If you forget your password use <a href="{{ new_password_view_url }}">New Password menu</a>
            to get a new password to your email address.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'new_user_info' %}
    <h3>
        {% blocktrans %}
        <p>Your wireless connection details were sent to the email address ({{ email }}).</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/check.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'guest_user_info' %}
    <h3>
        {% blocktrans %}
        <p>Your wireless connection details were sent to the email address ({{ email }}).</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/check.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'new_user_link_timeout' %}
    <h3>
        {% url new_user_view as new_user_view_url %}
        {% blocktrans %}
        <p>You haven't clicked the link in the defined timeout interval.</p>
        <p>Repeat your <a href="{{ new_user_view_url }}">New User</a> application.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'guest_user_link_timeout' %}
    <h3>
        {% url guest_user_view as guest_user_view_url %}
        {% blocktrans %}
        <p>You haven't clicked the link in the defined timeout interval.</p>
        <p>Repeat your <a href="{{ guest_user_view_url }}">Guest User</a> application.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'password_change_st_true'%}
    <h3>
        {% url new_password_view as new_password_view_url %}
        {% blocktrans %}
        <p>You had changed your password by clicking this link once.</p>
        <p>To change your password again use <a href="{{ new_password_view_url }}">New Password</a> menu.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'ldap_error' %}
    <h3>
        {% blocktrans %}
        <p>An error occured when your request is being processed.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% ifequal info 'expire_time' %}
    <h3>
        {% url new_password_view as new_password_view_url %}
        {% blocktrans %}
        <p>This link is timeout.</p>
        <p>Use <a href="{{ new_password_view_url }}">New Password</a> link and try again.</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/warning.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
    {% ifequal info 'host_user_info' %}
        {% blocktrans %}
        <h3>Username and password information is sent to your friend's email address.</h3>
        {% endblocktrans %}
    {% endifequal %}
{% ifequal info 'password_change_successful' %}
    <h3>
        {% blocktrans %}
        <p>Your new password was sent to your email address ({{ email }}).</p>
        {% endblocktrans %}
    </h3>
    <div class="row">
        <div class="offset4 span4">
            <img src="/site_media/images/check.png" alt="{% trans 'Warning' %}" >
        </div>
    </div>
{% endifequal %}
{% endblock %}
{% block language %}
{% endblock %}

templates/main/main.html
{% extends "main/base.html" %}
{% load i18n %}
{% block content %}
    <div class="hero-unit hero-logo">
        <div class="row">


            <div class="span4 offset4">
                <p align=center>
                    <img src="/site_media/images/comu_logo.png" alt="{% trans 'Çanakkale Onsekiz Mart University' %}" >
                </p>
                <h2>{% trans welcome_header %}</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span4">
            <ul class="thumbnails">
                <li class="span3">
                    <a href="{% url new_user_view %}" class="thumbnail">
                        <img src="/site_media/images/new_user.png" alt="{% trans 'Register' %}" ></a></li></ul>
            <h3>{% trans "New User" %}</h3>
        </div>

        <!--<div class="span4">
            <ul class="thumbnails">
                <li class="span3">
                        <a href="{% url guest_user_view %}" class="thumbnail">
                            <img src="/site_media/images/guest_user.png" alt="Misafir Kullanıcı " >
                        </a></li></ul>
            <h3>Misafir Kullanıcı</h3>
        </div>-->
        <div class="offset4 span4">
            <ul class="thumbnails">
                <li class="span3">
                        <a href="{% url new_password_view %}" class="thumbnail">
                            <img src="/site_media/images/password_change.png" alt="{% trans 'New Password' %}" >
                        </a>
                </li>
            </ul>
            <h3>{% trans "New Password" %}</h3>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <p class="lead">
                {% blocktrans %}
                From the <strong>New User</strong> menu fill the form with en email that has the extension of <strong>comu.edu.tr</strong>.
                After filling the form and clicking the link that is sent to your email, your connection credentials
                will be sent to your email.
                {% endblocktrans %}
            </p>
            <p class="lead">
                {% blocktrans %}
                If you have a wireless account already use <strong>New Password</strong> menu.
                After filling the form and clicking the link that is sent to your email, your connection credentials
                will be sent to your email.
                {% endblocktrans %}
            </p>
            <p class="lead">
                <small>{% trans "Çanakkale Onsekiz Mart University" %}</small>
                <small>Tel: 0286 218 00 18 - 1410</small>
               <small> <a href="http://bidb.comu.edu.tr"> {% trans "BIDB Main Page" %}</a></small>
                <small><a href="http://eduroam.comu.edu.tr"> {% trans "Eduroam Connection Settings" %}</a></small>
            </p>
        </div>
    </div>

{% endblock %}
{% block design %}
{% endblock %}